### ISSUE TITLE
List of assemblies does not contain the application's assembly.

### ISSUE THREAD

**Issue by SlyFoxHayes** [PandaWood/ExceptionReporter.NET#28]
In the list of assemblies below, there should be a "MainMenu.exe", which is assembly with the application.

![image](https://user-images.githubusercontent.com/42080100/43792542-fee48d96-9a46-11e8-9b07-1aa11ee66c14.png)

**Comment by PandaWood** [comment]
Right, it must just be because the `AssemblyReferenceDigger` only fetches referenced assemblies via `GetReferencedAssemblies` and doesn't include itself...

Though, this isn't quite that simple because we use this within an Office Addin and I believe that's the reason it's not easy to even know what the main calling code is, which I think is why we do this `Assembly.GetEntryAssembly() ?? Assembly.GetCallingAssembly()`

**Comment by PandaWood** [comment]
I believe this is fixed in the latest commit - I did a quick check on the demo and it looked right
