### ISSUE TITLE
SimpleMAPI mail no longer works?

### ISSUE THREAD

**Issue by chopsnsauce** [PandaWood/ExceptionReporter.NET#58]
Hello,

Getting this issue trying to email the error:

![image](https://user-images.githubusercontent.com/65713299/111306347-05ef3300-8650-11eb-8f12-71592be39f6b.png)

Downloaded the Nuget and it comes up with manifest warnings for 2 of the dependencies.  Updated them through Nuget and the warnings go away, but email still doesn't work. I'm trying to use this in a .Net framework 4.8 WinForms project.

Is this an issue or am I doing something wrong?

Thanks,

Nick

**Comment by PandaWood** [comment]
Hey, well "HandlebarsDotNet" is a library dependency - for the whole of ExceptionReporter. So this won't be specific to SimpleMAPI - it's just that sending anything uses the Handlebars template library before being sent.

It looks like one of the methods (Compile())is not being found so that's a lower level problem - it would have to be either the wrong/corrupt nuget dependency or .Net version incompatibility.

I would have thought that errors like this is what Nuget is designed to avoid, so something at that level.
If you can fork a version with your exact project in it's current state, I can check if it happens for me.
I'm not really sure what you mean by getting "manifest warnings" - I probably need to know exactly what you did to get there and what the warning message is.

**Comment by chopsnsauce** [comment]
Hiya,

Thanks for getting back to me, manifest warnings were around it 'knowing' about later versions of those libraries and not finding them (Which maybe suggests there's something wrong with the Nuget?)

The projects not in git, so I can't share the code I'm afraid.  but in theory this should be repeatable by just creating a new WinForms 4.8 framework project and downloading the Nuget.

I've rolled back to our previous method of doing this now, so it's not like I'm stuck on this or anything.
